<?php

return [
    'apotek' => [
        'label_product'   => 'Obat',
        'label_location'  => 'Rak',
        'label_supplier'  => 'Distributor',
        'label_customer'  => 'Pelanggan',
        'label_purchase'  => 'Pembelian',
        'label_category'  => 'Kategori Obat',
        'label_unit'      => 'Satuan',
        'show_product_location' => true,
        'show_product_content'  => true,
        'trx_prefix'      => 'PJ',
    ],
    'retail' => [
        'label_product'   => 'Produk',
        'label_location'  => 'Lokasi',
        'label_supplier'  => 'Supplier',
        'label_customer'  => 'Pelanggan',
        'label_purchase'  => 'Pembelian',
        'label_category'  => 'Kategori',
        'label_unit'      => 'Satuan',
        'show_product_location' => true,
        'show_product_content'  => false,
        'trx_prefix'      => 'INV',
    ],
    'fnb' => [
        'label_product'   => 'Menu',
        'label_location'  => 'Area',
        'label_supplier'  => 'Vendor',
        'label_customer'  => 'Tamu',
        'label_purchase'  => 'Pengadaan',
        'label_category'  => 'Kategori Menu',
        'label_unit'      => 'Porsi',
        'show_product_location' => false,
        'show_product_content'  => false,
        'trx_prefix'      => 'ORD',
    ],
    'general' => [
        'label_product'   => 'Produk',
        'label_location'  => 'Lokasi',
        'label_supplier'  => 'Supplier',
        'label_customer'  => 'Pelanggan',
        'label_purchase'  => 'Pembelian',
        'label_category'  => 'Kategori',
        'label_unit'      => 'Satuan',
        'show_product_location' => true,
        'show_product_content'  => false,
        'trx_prefix'      => 'TRX',
    ],
];
